pipeline {
  agent any

  environment {
						
						url = "https://github.com/Surajjadhav97/My-Nodejs-project.git"
  }
  
 stages {  
       stage ("ClONE_PROJECT"){
								
							steps {
										sh "rm -rf *"
										sh "git clone $url"
							
							}
       }
   
    stage('Build') {
      steps {
        script {
          docker.build('nodejs-web-server')
        }
      }
    }

   

    stage('Deploy') {
      steps {
        script {
          docker.withRegistry('https://hub.docker.com/u/surajjadhav97', 'docker-credentials') {
            docker.image('nodejs-web-server').push()
          }
        }
      }
    }
  }
}

