pipeline {
  agent any

  environment {
						
		url = "https://github.com/Surajjadhav97/My-Nodejs-project.git"
  }
  
 stages {  
       stage ("ClONE_PROJECT"){
								
	 steps {
		sh "rm -rf *"
		sh "git clone $url"
							
		}
       }

    stage ("Node.js"){
	    steps{
		 sh "npm install express --save"
		 sh "npm start"
		 sh "nohup node index.js > output.log 2>&1 &" 
	    }
       }

    stage('Build') {
          steps {
          script {
          sh "docker build -t <image-name> ."
	  sh "docker run -d -p 3000:3000 <your-image-name>"
	  
        }
      }
    }

   
   stage('Deploy') {
      steps {
        script {
          docker.withRegistry('https://hub.docker.com/u/surajjadhav97', 'docker-credentials') {
            docker.image('nodejs-web-server').push()
          }
        }
      }
    }
  }

